### ISSUE TITLE
Einstellungen für "Dauerläufer"

### ISSUE THREAD

**Issue by herrdeh** [jowi24/vdr-fritz#4]
Mein VDR/MLD läuft (ununterbrochen) auf einem RPi4; ich habe Monate damit verbracht rauszukriegen, daß es das FritzBox-Plugin ist, das mir ständig Aufnahmen erzeugt. Insofern möchte ich folgende Einstellmöglichkeiten für ständig laufende VDR-Systeme anregen:

- markiere Aufnahmen mit "FB" o.ä., wenn von Fritzbox erzeugt - damit man sie zuordnen kann
- ermögliche in den Einstellungen des Plugins eine zusätzliche Längenbegrenzung für von FB erzeugte Aufnahmen 
- ermögliche in den Einstellungen des Plugins eine automatische Löschung von FB-Aufnahmen, zum Beispiel nach einem Tag.

Ideal wäre wohl, keine Aufnahmen bei ausgeschaltetem Bildschirm zu erzeugen - aber ich weiß nicht, ob ein Rechner zuverlässig mitkriegen kann, ob der Bildschirm an/aus/im Ruhezustand ist.

**Comment by jowi24** [comment]
Hallo @herrdeh, das FritzBox-Plugin erzeugt keine Aufnahmen. Das ist die VDR-eigene Funktion "Time-Shift", siehe http://www.vdr-wiki.de/wiki/index.php/Benutzerhandbuch#Pause_f.C3.BCr_ein_Live-Signal_.28Time_Shift.29

Du kannst das Verhalten beeinflussen, indem Du im Fritzbox-Plugin die Optionen "Live-TV pausieren" wie gewünscht konfigurierst.
